//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("collectstikersModel", "FK_STICKERS_REFERENCE_ALBUM", "Album", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CollectStickers.Models.Album), "Stickers", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CollectStickers.Models.Stickers))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("collectstikersModel", "FK_Stickers_aspnet_Users", "aspnet_Users", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CollectStickers.Models.aspnet_Users), "Stickers", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CollectStickers.Models.Stickers))]

// Original file name:
// Generation date: 11.11.2009 16:45:52
namespace CollectStickers.Models
{
    
    /// <summary>
    /// There are no comments for collectstikersEntities1 in the schema.
    /// </summary>
    public partial class StickersStorage : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new collectstikersEntities1 object using the connection string found in the 'collectstikersEntities1' section of the application configuration file.
        /// </summary>
        public StickersStorage() : 
                base("name=collectstikersEntities1", "collectstikersEntities1")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new collectstikersEntities1 object.
        /// </summary>
        public StickersStorage(string connectionString) : 
                base(connectionString, "collectstikersEntities1")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new collectstikersEntities1 object.
        /// </summary>
        public StickersStorage(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "collectstikersEntities1")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Album in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Album> Album
        {
            get
            {
                if ((this._Album == null))
                {
                    this._Album = base.CreateQuery<Album>("[Album]");
                }
                return this._Album;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Album> _Album;
        /// <summary>
        /// There are no comments for aspnet_Users in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<aspnet_Users> aspnet_Users
        {
            get
            {
                if ((this._aspnet_Users == null))
                {
                    this._aspnet_Users = base.CreateQuery<aspnet_Users>("[aspnet_Users]");
                }
                return this._aspnet_Users;
            }
        }
        private global::System.Data.Objects.ObjectQuery<aspnet_Users> _aspnet_Users;
        /// <summary>
        /// There are no comments for Stickers in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Stickers> Stickers
        {
            get
            {
                if ((this._Stickers == null))
                {
                    this._Stickers = base.CreateQuery<Stickers>("[Stickers]");
                }
                return this._Stickers;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Stickers> _Stickers;
        /// <summary>
        /// There are no comments for Album in the schema.
        /// </summary>
        public void AddToAlbum(Album album)
        {
            base.AddObject("Album", album);
        }
        /// <summary>
        /// There are no comments for aspnet_Users in the schema.
        /// </summary>
        public void AddToaspnet_Users(aspnet_Users aspnet_Users)
        {
            base.AddObject("aspnet_Users", aspnet_Users);
        }
        /// <summary>
        /// There are no comments for Stickers in the schema.
        /// </summary>
        public void AddToStickers(Stickers stickers)
        {
            base.AddObject("Stickers", stickers);
        }
    }
    /// <summary>
    /// There are no comments for collectstikersModel.Album in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="collectstikersModel", Name="Album")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Album : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Album object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        public static Album CreateAlbum(short id)
        {
            Album album = new Album();
            album.Id = id;
            return album;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private short _Id;
        partial void OnIdChanging(short value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property MaxStickers in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<short> MaxStickers
        {
            get
            {
                return this._MaxStickers;
            }
            set
            {
                this.OnMaxStickersChanging(value);
                this.ReportPropertyChanging("MaxStickers");
                this._MaxStickers = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MaxStickers");
                this.OnMaxStickersChanged();
            }
        }
        private global::System.Nullable<short> _MaxStickers;
        partial void OnMaxStickersChanging(global::System.Nullable<short> value);
        partial void OnMaxStickersChanged();
        /// <summary>
        /// There are no comments for Stickers in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("collectstikersModel", "FK_STICKERS_REFERENCE_ALBUM", "Stickers")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Stickers> Stickers
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Stickers>("collectstikersModel.FK_STICKERS_REFERENCE_ALBUM", "Stickers");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Stickers>("collectstikersModel.FK_STICKERS_REFERENCE_ALBUM", "Stickers", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for collectstikersModel.aspnet_Users in the schema.
    /// </summary>
    /// <KeyProperties>
    /// UserId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="collectstikersModel", Name="aspnet_Users")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class aspnet_Users : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new aspnet_Users object.
        /// </summary>
        /// <param name="applicationId">Initial value of ApplicationId.</param>
        /// <param name="userId">Initial value of UserId.</param>
        /// <param name="userName">Initial value of UserName.</param>
        /// <param name="loweredUserName">Initial value of LoweredUserName.</param>
        /// <param name="isAnonymous">Initial value of IsAnonymous.</param>
        /// <param name="lastActivityDate">Initial value of LastActivityDate.</param>
        public static aspnet_Users Createaspnet_Users(global::System.Guid applicationId, global::System.Guid userId, string userName, string loweredUserName, bool isAnonymous, global::System.DateTime lastActivityDate)
        {
            aspnet_Users aspnet_Users = new aspnet_Users();
            aspnet_Users.ApplicationId = applicationId;
            aspnet_Users.UserId = userId;
            aspnet_Users.UserName = userName;
            aspnet_Users.LoweredUserName = loweredUserName;
            aspnet_Users.IsAnonymous = isAnonymous;
            aspnet_Users.LastActivityDate = lastActivityDate;
            return aspnet_Users;
        }
        /// <summary>
        /// There are no comments for Property ApplicationId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid ApplicationId
        {
            get
            {
                return this._ApplicationId;
            }
            set
            {
                this.OnApplicationIdChanging(value);
                this.ReportPropertyChanging("ApplicationId");
                this._ApplicationId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ApplicationId");
                this.OnApplicationIdChanged();
            }
        }
        private global::System.Guid _ApplicationId;
        partial void OnApplicationIdChanging(global::System.Guid value);
        partial void OnApplicationIdChanged();
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this.ReportPropertyChanging("UserId");
                this._UserId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UserId");
                this.OnUserIdChanged();
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this.ReportPropertyChanging("UserName");
                this._UserName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("UserName");
                this.OnUserNameChanged();
            }
        }
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property LoweredUserName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LoweredUserName
        {
            get
            {
                return this._LoweredUserName;
            }
            set
            {
                this.OnLoweredUserNameChanging(value);
                this.ReportPropertyChanging("LoweredUserName");
                this._LoweredUserName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("LoweredUserName");
                this.OnLoweredUserNameChanged();
            }
        }
        private string _LoweredUserName;
        partial void OnLoweredUserNameChanging(string value);
        partial void OnLoweredUserNameChanged();
        /// <summary>
        /// There are no comments for Property MobileAlias in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileAlias
        {
            get
            {
                return this._MobileAlias;
            }
            set
            {
                this.OnMobileAliasChanging(value);
                this.ReportPropertyChanging("MobileAlias");
                this._MobileAlias = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("MobileAlias");
                this.OnMobileAliasChanged();
            }
        }
        private string _MobileAlias;
        partial void OnMobileAliasChanging(string value);
        partial void OnMobileAliasChanged();
        /// <summary>
        /// There are no comments for Property IsAnonymous in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAnonymous
        {
            get
            {
                return this._IsAnonymous;
            }
            set
            {
                this.OnIsAnonymousChanging(value);
                this.ReportPropertyChanging("IsAnonymous");
                this._IsAnonymous = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsAnonymous");
                this.OnIsAnonymousChanged();
            }
        }
        private bool _IsAnonymous;
        partial void OnIsAnonymousChanging(bool value);
        partial void OnIsAnonymousChanged();
        /// <summary>
        /// There are no comments for Property LastActivityDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime LastActivityDate
        {
            get
            {
                return this._LastActivityDate;
            }
            set
            {
                this.OnLastActivityDateChanging(value);
                this.ReportPropertyChanging("LastActivityDate");
                this._LastActivityDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LastActivityDate");
                this.OnLastActivityDateChanged();
            }
        }
        private global::System.DateTime _LastActivityDate;
        partial void OnLastActivityDateChanging(global::System.DateTime value);
        partial void OnLastActivityDateChanged();
        /// <summary>
        /// There are no comments for Stickers in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("collectstikersModel", "FK_Stickers_aspnet_Users", "Stickers")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Stickers> Stickers
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Stickers>("collectstikersModel.FK_Stickers_aspnet_Users", "Stickers");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Stickers>("collectstikersModel.FK_Stickers_aspnet_Users", "Stickers", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for collectstikersModel.Stickers in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="collectstikersModel", Name="Stickers")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Stickers : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Stickers object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="needOrFree">Initial value of NeedOrFree.</param>
        /// <param name="number">Initial value of Number.</param>
        public static Stickers CreateStickers(int id, byte needOrFree, short number)
        {
            Stickers stickers = new Stickers();
            stickers.Id = id;
            stickers.NeedOrFree = needOrFree;
            stickers.Number = number;
            return stickers;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property NeedOrFree in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte NeedOrFree
        {
            get
            {
                return this._NeedOrFree;
            }
            set
            {
                this.OnNeedOrFreeChanging(value);
                this.ReportPropertyChanging("NeedOrFree");
                this._NeedOrFree = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NeedOrFree");
                this.OnNeedOrFreeChanged();
            }
        }
        private byte _NeedOrFree;
        partial void OnNeedOrFreeChanging(byte value);
        partial void OnNeedOrFreeChanged();
        /// <summary>
        /// There are no comments for Property Number in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short Number
        {
            get
            {
                return this._Number;
            }
            set
            {
                this.OnNumberChanging(value);
                this.ReportPropertyChanging("Number");
                this._Number = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Number");
                this.OnNumberChanged();
            }
        }
        private short _Number;
        partial void OnNumberChanging(short value);
        partial void OnNumberChanged();
        /// <summary>
        /// There are no comments for Album in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("collectstikersModel", "FK_STICKERS_REFERENCE_ALBUM", "Album")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Album Album
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Album>("collectstikersModel.FK_STICKERS_REFERENCE_ALBUM", "Album").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Album>("collectstikersModel.FK_STICKERS_REFERENCE_ALBUM", "Album").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Album in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Album> AlbumReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Album>("collectstikersModel.FK_STICKERS_REFERENCE_ALBUM", "Album");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Album>("collectstikersModel.FK_STICKERS_REFERENCE_ALBUM", "Album", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for aspnet_Users in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("collectstikersModel", "FK_Stickers_aspnet_Users", "aspnet_Users")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public aspnet_Users aspnet_Users
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<aspnet_Users>("collectstikersModel.FK_Stickers_aspnet_Users", "aspnet_Users").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<aspnet_Users>("collectstikersModel.FK_Stickers_aspnet_Users", "aspnet_Users").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for aspnet_Users in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<aspnet_Users> aspnet_UsersReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<aspnet_Users>("collectstikersModel.FK_Stickers_aspnet_Users", "aspnet_Users");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<aspnet_Users>("collectstikersModel.FK_Stickers_aspnet_Users", "aspnet_Users", value);
                }
            }
        }
    }
}
