//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Portfolio", "DesignerDesignerContent", "Designer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Listelli.Models.Designer), "DesignerContent", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Listelli.Models.DesignerContent), true)]
[assembly: EdmRelationshipAttribute("Portfolio", "DesignerContentDesignerContantImage", "DesignerContent", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Listelli.Models.DesignerContent), "DesignerContantImage", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Listelli.Models.DesignerContantImage), true)]

#endregion

namespace Listelli.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PortfolioContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PortfolioContainer object using the connection string found in the 'PortfolioContainer' section of the application configuration file.
        /// </summary>
        public PortfolioContainer() : base("name=PortfolioContainer", "PortfolioContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PortfolioContainer object.
        /// </summary>
        public PortfolioContainer(string connectionString) : base(connectionString, "PortfolioContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PortfolioContainer object.
        /// </summary>
        public PortfolioContainer(EntityConnection connection) : base(connection, "PortfolioContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Designer> Designer
        {
            get
            {
                if ((_Designer == null))
                {
                    _Designer = base.CreateObjectSet<Designer>("Designer");
                }
                return _Designer;
            }
        }
        private ObjectSet<Designer> _Designer;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DesignerContent> DesignerContent
        {
            get
            {
                if ((_DesignerContent == null))
                {
                    _DesignerContent = base.CreateObjectSet<DesignerContent>("DesignerContent");
                }
                return _DesignerContent;
            }
        }
        private ObjectSet<DesignerContent> _DesignerContent;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DesignerContantImage> DesignerContantImage
        {
            get
            {
                if ((_DesignerContantImage == null))
                {
                    _DesignerContantImage = base.CreateObjectSet<DesignerContantImage>("DesignerContantImage");
                }
                return _DesignerContantImage;
            }
        }
        private ObjectSet<DesignerContantImage> _DesignerContantImage;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Designer EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDesigner(Designer designer)
        {
            base.AddObject("Designer", designer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DesignerContent EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDesignerContent(DesignerContent designerContent)
        {
            base.AddObject("DesignerContent", designerContent);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DesignerContantImage EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDesignerContantImage(DesignerContantImage designerContantImage)
        {
            base.AddObject("DesignerContantImage", designerContantImage);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Portfolio", Name="Designer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Designer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Designer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="designerName">Initial value of the DesignerName property.</param>
        /// <param name="designerNameF">Initial value of the DesignerNameF property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="imageSource">Initial value of the ImageSource property.</param>
        public static Designer CreateDesigner(global::System.Int32 id, global::System.String name, global::System.String designerName, global::System.String designerNameF, global::System.String description, global::System.String imageSource)
        {
            Designer designer = new Designer();
            designer.Id = id;
            designer.Name = name;
            designer.DesignerName = designerName;
            designer.DesignerNameF = designerNameF;
            designer.Description = description;
            designer.ImageSource = imageSource;
            return designer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DesignerName
        {
            get
            {
                return _DesignerName;
            }
            set
            {
                OnDesignerNameChanging(value);
                ReportPropertyChanging("DesignerName");
                _DesignerName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DesignerName");
                OnDesignerNameChanged();
            }
        }
        private global::System.String _DesignerName;
        partial void OnDesignerNameChanging(global::System.String value);
        partial void OnDesignerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DesignerNameF
        {
            get
            {
                return _DesignerNameF;
            }
            set
            {
                OnDesignerNameFChanging(value);
                ReportPropertyChanging("DesignerNameF");
                _DesignerNameF = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DesignerNameF");
                OnDesignerNameFChanged();
            }
        }
        private global::System.String _DesignerNameF;
        partial void OnDesignerNameFChanging(global::System.String value);
        partial void OnDesignerNameFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ImageSource
        {
            get
            {
                return _ImageSource;
            }
            set
            {
                OnImageSourceChanging(value);
                ReportPropertyChanging("ImageSource");
                _ImageSource = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ImageSource");
                OnImageSourceChanged();
            }
        }
        private global::System.String _ImageSource;
        partial void OnImageSourceChanging(global::System.String value);
        partial void OnImageSourceChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Portfolio", "DesignerDesignerContent", "DesignerContent")]
        public EntityCollection<DesignerContent> DesignerContents
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DesignerContent>("Portfolio.DesignerDesignerContent", "DesignerContent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DesignerContent>("Portfolio.DesignerDesignerContent", "DesignerContent", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Portfolio", Name="DesignerContantImage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DesignerContantImage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DesignerContantImage object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="designerContentId">Initial value of the DesignerContentId property.</param>
        /// <param name="imageSource">Initial value of the ImageSource property.</param>
        public static DesignerContantImage CreateDesignerContantImage(global::System.Int32 id, global::System.Int32 designerContentId, global::System.String imageSource)
        {
            DesignerContantImage designerContantImage = new DesignerContantImage();
            designerContantImage.Id = id;
            designerContantImage.DesignerContentId = designerContentId;
            designerContantImage.ImageSource = imageSource;
            return designerContantImage;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DesignerContentId
        {
            get
            {
                return _DesignerContentId;
            }
            set
            {
                OnDesignerContentIdChanging(value);
                ReportPropertyChanging("DesignerContentId");
                _DesignerContentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DesignerContentId");
                OnDesignerContentIdChanged();
            }
        }
        private global::System.Int32 _DesignerContentId;
        partial void OnDesignerContentIdChanging(global::System.Int32 value);
        partial void OnDesignerContentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ImageSource
        {
            get
            {
                return _ImageSource;
            }
            set
            {
                OnImageSourceChanging(value);
                ReportPropertyChanging("ImageSource");
                _ImageSource = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ImageSource");
                OnImageSourceChanged();
            }
        }
        private global::System.String _ImageSource;
        partial void OnImageSourceChanging(global::System.String value);
        partial void OnImageSourceChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Portfolio", "DesignerContentDesignerContantImage", "DesignerContent")]
        public DesignerContent DesignerContent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DesignerContent>("Portfolio.DesignerContentDesignerContantImage", "DesignerContent").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DesignerContent>("Portfolio.DesignerContentDesignerContantImage", "DesignerContent").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DesignerContent> DesignerContentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DesignerContent>("Portfolio.DesignerContentDesignerContantImage", "DesignerContent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DesignerContent>("Portfolio.DesignerContentDesignerContantImage", "DesignerContent", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Portfolio", Name="DesignerContent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DesignerContent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DesignerContent object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="designerId">Initial value of the DesignerId property.</param>
        /// <param name="roomType">Initial value of the RoomType property.</param>
        /// <param name="roomTitle">Initial value of the RoomTitle property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static DesignerContent CreateDesignerContent(global::System.Int32 id, global::System.Int32 designerId, global::System.String roomType, global::System.String roomTitle, global::System.String description)
        {
            DesignerContent designerContent = new DesignerContent();
            designerContent.Id = id;
            designerContent.DesignerId = designerId;
            designerContent.RoomType = roomType;
            designerContent.RoomTitle = roomTitle;
            designerContent.Description = description;
            return designerContent;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DesignerId
        {
            get
            {
                return _DesignerId;
            }
            set
            {
                OnDesignerIdChanging(value);
                ReportPropertyChanging("DesignerId");
                _DesignerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DesignerId");
                OnDesignerIdChanged();
            }
        }
        private global::System.Int32 _DesignerId;
        partial void OnDesignerIdChanging(global::System.Int32 value);
        partial void OnDesignerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RoomType
        {
            get
            {
                return _RoomType;
            }
            set
            {
                OnRoomTypeChanging(value);
                ReportPropertyChanging("RoomType");
                _RoomType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RoomType");
                OnRoomTypeChanged();
            }
        }
        private global::System.String _RoomType;
        partial void OnRoomTypeChanging(global::System.String value);
        partial void OnRoomTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RoomTitle
        {
            get
            {
                return _RoomTitle;
            }
            set
            {
                OnRoomTitleChanging(value);
                ReportPropertyChanging("RoomTitle");
                _RoomTitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RoomTitle");
                OnRoomTitleChanged();
            }
        }
        private global::System.String _RoomTitle;
        partial void OnRoomTitleChanging(global::System.String value);
        partial void OnRoomTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Portfolio", "DesignerDesignerContent", "Designer")]
        public Designer Designer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Designer>("Portfolio.DesignerDesignerContent", "Designer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Designer>("Portfolio.DesignerDesignerContent", "Designer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Designer> DesignerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Designer>("Portfolio.DesignerDesignerContent", "Designer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Designer>("Portfolio.DesignerDesignerContent", "Designer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Portfolio", "DesignerContentDesignerContantImage", "DesignerContantImage")]
        public EntityCollection<DesignerContantImage> DesignerContantImages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DesignerContantImage>("Portfolio.DesignerContentDesignerContantImage", "DesignerContantImage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DesignerContantImage>("Portfolio.DesignerContentDesignerContantImage", "DesignerContantImage", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
