//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiki.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attention
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public string ImageSource { get; set; }
    }
}
