//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryService.DataAccess.Db.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.MasterCategories = new HashSet<MasterCategory>();
            this.CompanyLocalInfo = new HashSet<CompanyLocalInfo>();
            this.ProductLocalInfo = new HashSet<ProductLocalInfo>();
            this.Companies = new HashSet<Company>();
            this.CategoryLocalInfo = new HashSet<CategoryLocalInfo>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<MasterCategory> MasterCategories { get; set; }
        public virtual ICollection<CompanyLocalInfo> CompanyLocalInfo { get; set; }
        public virtual ICollection<ProductLocalInfo> ProductLocalInfo { get; set; }
        public virtual ICollection<Company> Companies { get; set; }
        public virtual ICollection<CategoryLocalInfo> CategoryLocalInfo { get; set; }
    }
}
