//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewVision.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArtWorkContainer : DbContext
    {
        public ArtWorkContainer()
            : base("name=ArtWorkContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Language> Language { get; set; }
        public DbSet<Author> Author { get; set; }
        public DbSet<Tag> Tag { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<AuthorLang> AuthorLang { get; set; }
        public DbSet<ProductLang> ProductLang { get; set; }
        public DbSet<TagLang> TagLang { get; set; }
        public DbSet<AuthorCategory> AuthorCategory { get; set; }
        public DbSet<AuthorCategoryLang> AuthorCategoryLang { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<CategoryLang> CategoryLang { get; set; }
    }
}
