//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewVision.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.Authors = new HashSet<Author>();
            this.AuthorCategories = new HashSet<AuthorCategory>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string TitleEn { get; set; }
        public string TitleUa { get; set; }
    
        public virtual ICollection<Author> Authors { get; set; }
        public virtual ICollection<AuthorCategory> AuthorCategories { get; set; }
    }
}
