//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM2014
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductItem
    {
        public int Id { get; set; }
        public int SortOrder { get; set; }
        public string Text { get; set; }
        public string ImageSource { get; set; }
        public int ProductId { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
