//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryService.DataAccess.Db.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterCategory
    {
        public MasterCategory()
        {
            this.Cities = new HashSet<City>();
            this.Companies = new HashSet<Company>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<City> Cities { get; set; }
        public virtual ICollection<Company> Companies { get; set; }
    }
}
