//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleItemLang
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public int ArticleItemId { get; set; }
        public int LanguageId { get; set; }
    
        public virtual ArticleItem ArticleItem { get; set; }
        public virtual Language Language { get; set; }
    }
}
